#!/bin/bash

# Setup vim
mkdir -p ~/.vim/backup/
mkdir -p ~/.vim/swap/
mkdir -p ~/.vim/undo/
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
mv ~/.bashrc ~/.bashrc-archive

# Symlink conf
ln -fs ~/dotfiles/vim ~/.vim
ln -fs ~/dotfiles/vimrc ~/.vimrc
ln -fs ~/dotfiles/bashrc ~/.bashrc

if [[ $(uname) == "Darwin" ]]; then
  ln -fs ~/dotfiles/tmux.conf ~/.tmux.conf
else
  ln -fs ~/dotfiles/remote-tmux.conf ~/.tmux.conf
fi
